Globally scope ActiveRecord constant lookup
Without this, `ActiveRecord::Base.internal_metadata_table_name` resolves
to the `DatabaseCleaner::ActiveRecord::Base`, which doesn't have that
method. This means trying to run with a truncation strategy on Rails >=
5 results in the following error:

    NoMethodError:
      undefined method `internal_metadata_table_name' for DatabaseCleaner::ActiveRecord::Base:Module

Phew!